// <auto-generated />
namespace Baker_Point.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ji : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ji));
        
        string IMigrationMetadata.Id
        {
            get { return "201706021005476_ji"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
